### ISSUE TITLE
Easy mapping to objects

### ISSUE THREAD

**Issue by Agrosis** [plasmaconduit/json#3]
I know you can already get a Map[String, String] back from a JsObject, but would it be possible to take it one step further and write your own mappers so you could convert a JsObject to a case class of your choice?

Something like http://stackoverflow.com/questions/20684572/scala-convert-map-to-case-class

**Comment by JosephMoniz** [comment]
Yeah, thats what i was trying to get at w/ my validation lib: https://github.com/plasmaconduit/validators

It can take form input (Map[String, String]) and json input, perform some validation and produce a strongly typed object. It works w/ primitives and w/ complex nested object types as well.

The validation lib has lots of boiler plate though. I can make it simpler to use if i were to write some macros for it but the Scala team at TypeSafe is currently in the process of completely redoing the macro system so i've been putting it off till then. Might be worth it to bite the bullet and do it anyways though.

**Comment by Agrosis** [comment]
Oh ok that's awesome thanks
